Разработка фичи add-most-populars 2024.11.10
quququhead/java-filmorate pull request #11
Opened 2024-11-10 13:28 UTC by Daniiland96

Разработка фичи add-most-populars

2024-11-10 13:44 UTC, Lucky7456 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                         @RequestParam(name = "year", required = false) Integer year) {
необязательно указывать name, если название переменной совпадает с параметром запроса

2024-11-10 13:51 UTC, Lucky7456 commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +            " LEFT JOIN likes l ON l.film_id = f.film_id LEFT JOIN film_genres fg ON fg.film_id = f.film_id" +
джоин жанров лишний в запросе по дате

2024-11-10 14:08 UTC, Lucky7456 requested changes
в целом ок, чуть поправить и готово

2024-11-10 14:30 UTC, Lucky7456 approved these changes
отлично!

2024-11-11 08:47 UTC, quququhead approved these changes

2024-11-11 08:53 UTC, merged